/*
 * Kuju API
 *
 * Kuju API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Zubin.Platform.WebApi2.PythonAiApi.Models
{
    /// <summary>
    /// 
    public class GetRecommendationResponse
    {
        public List<Event> Events { get; set; }
    }
}
