/*
 * Kuju API
 *
 * Kuju API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using MockServer.SwaggerEditor.PythonAi.Models;

namespace MockServer.SwaggerEditor.PythonApi.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PythonAiApiController : ControllerBase
    {
        /// <summary>
        /// ControlDevice
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/chatbox")]
        [ValidateModelState]
        [SwaggerOperation("sendMessage")]
        [SwaggerResponse(statusCode: 200, type: typeof(SendMessageResponse), description: "Success")]
        public virtual IActionResult SendMessage([FromBody] SendMessageRequest body)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ControlDeviceResponse));
            string exampleJson = null;
            exampleJson = "{\n  \"msg\" : \"msg\",\n  \"result\" : \"result\",\n  \"code\" : \"code\",\n  \"info\" : \"info\"\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<SendMessageResponse>(exampleJson)
            : default;            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
