/*
 * Kuju API
 *
 * Kuju API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace MockServer.SwaggerEditor.PythonAiApi.Models
{
    public class ResponseEvent
    {
        public string Eventid { get; set; }
        public decimal Similarity { get; set; }
    }
}
